# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0709fa24a4f56fcf4d327cd1947ea60a314ac62a51f459e2c1f0ae76380bb720e1d9b2bae8931678df14ea2b246d133f295276f8f58c9520593302334131d5f5

test:
  secret_key_base: 7e23efc39235fd96c76a89d84a2d4ac1a47c2f488f7ed6326ded606a77cf5efd914d026906b4579a7bbc17b599cfc4570b0d9ba7dd1f69512b6b3bc1c39587f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
